name: Daily Update from Dark Visitors


jobs:
  dark-visitors:
    runs-on: ubuntu-latest
    name: dark-visitors
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - run: |
          pip install beautifulsoup4 requests
          git config --global user.name "dark-visitors"
          git config --global user.email "dark-visitors@users.noreply.github.com"
          python code/dark_visitors.py
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Daily update from Dark Visitors" && git push)
        shell: bash
  call-main:
    needs: dark-visitors
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      message: "Daily update from Dark Visitors"